### ISSUE TITLE
[Feature] Publish this provider to hashicorp registry

### ISSUE THREAD

**Issue by jb-abbadie** [rhythmictech/terraform-provider-errorcheck#5]
With Terraform 0.13 released we can now publish providers to [terraform registry](https://registry.terraform.io/).
Having a provider in the registry makes it easier for user to download/use the provider.

The publishing process is quite easy : https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by cdaniluk** [comment]
Agreed. We have been holding our repos back to tf0.12 so haven't tackled this yet, but it's easy. I should be able to get it taken care of next week.

**Comment by cdaniluk** [comment]
and then I see that @sblack4 is secretly already working on this in a draft PR

**Comment by sblack4** [comment]
It's no secret, feel free to take over

**Comment by sblack4** [comment]
:D we have the first release up! https://registry.terraform.io/providers/rhythmictech/errorcheck/latest

It's marked RC, once #6 gets merged into master it should push `v2.0.4`
