### ISSUE TITLE
[BUG]: Update provider script is not working with latest version (tag)

### ISSUE THREAD

**Issue by art-cmyk** [rhythmictech/terraform-provider-errorcheck#7]
**Describe the bug**
Tag = v2.0.4-rc3
Assets = terraform-provider-errorcheck_2.0.4-rc3_darwin_amd64.zip

Tag should be 2.0.4-rc3
Assets should be terraform-provider-errorcheck_v2.0.4-rc3_darwin_amd64.zip

**To Reproduce**
1. Run the update provider script

**Expected behavior**
The latest version should be downloaded and terraform init should succeed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**

**Comment by sblack4** [comment]
It looks like there are some backward-compatibility issues for Terraform v0.12 now that we've released the v0.13 provider. Let me see if there's a quick work-around

**Comment by sblack4** [comment]
If you are on v0.13 you don't need to run that script though!

**Comment by sblack4** [comment]
I've got a work-around for you that should work! Pass the version that works for `v0.12` into the shell script, like so:

```
curl -sSL \
    https://raw.githubusercontent.com/rhythmictech/terraform-provider-errorcheck/master/update-provider.sh \
    | bash -s 2.0.3
```

My playground is here: https://github.com/sblack4/terraform-provider-errorcheck-examples/tree/terraform-v0.12

**Comment by art-cmyk** [comment]
@sblack4, thanks for the workaround. It works. Yes, unfortunately, we are still using terraform v0.12. I will try your provider with 0.13 on a different machine.

Anyway, I think the backwards compatibility fix would be great. Also, as a suggestion, I think it would be good to exclude release candidate version from the update provider script as they are not really release versions.

**Comment by smiller171** [comment]
I've fixed the release candidate to be marked as pre-release so it won't automatically download as `latest`

**Comment by smiller171** [comment]
@ravitej-aluru I've just released a new version of this that's actually just a module rather than a provider, but provides the same functionality. I'll be updating the docs on this repo soon to point to it as it's much simpler to get a custom module running than a provider. We're not planning on deprecating the provider immediately, but I think all use-cases can be covered by this new module.

https://registry.terraform.io/modules/rhythmictech/errorcheck/terraform/1.0.0
